# Generated by Django 5.1.7 on 2025-03-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movieembedding",
            index=models.Index(fields=["movie"], name="recommendat_movie_i_8171c9_idx"),
        ),
    ]
