# Generated by Django 5.1.7 on 2025-03-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("genres", models.TextField()),
                ("keywords", models.TextField()),
                ("overview", models.TextField()),
                ("popularity", models.FloatField()),
                ("production", models.TextField()),
                ("runtime", models.FloatField(blank=True, null=True)),
                ("tagline", models.TextField(blank=True, null=True)),
                ("vote_average", models.FloatField()),
                ("vote_count", models.IntegerField()),
                ("budget", models.BigIntegerField()),
            ],
        ),
    ]
